USE FlowerStore
GO
-- Create disk based tables
CREATE TABLE Flower
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FlowerName VARCHAR(30) NOT NULL,
	UnitPrice DECIMAL(4, 2) NOT NULL
);

INSERT INTO Flower VALUES
('Rose',		1.50),
('Hialeah',		1.25),
('Lilly',		0.75),
('Poinciana',	0.50),
('Daisy',		0.25);

CREATE TABLE Sale
(
	Id INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	SaleDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE LineItem
(
	Id INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	SaleId INT NOT NULL,
	FlowerId INT NOT NULL,
	Quantity INT NOT NULL,
	CONSTRAINT FK_Sale FOREIGN KEY (SaleId) REFERENCES Sale(Id),
	CONSTRAINT FK_Flower FOREIGN KEY (FlowerId) REFERENCES Flower(Id)
);

-- Adding Sales Data
INSERT INTO Sale VALUES
(GETDATE()),
(DATEADD(DD, -1, GETDATE())),
(DATEADD(DD, -2, GETDATE())),
(DATEADD(DD, -3, GETDATE())),
(DATEADD(DD, -4, GETDATE())),
(DATEADD(DD, -5, GETDATE()));

INSERT INTO Sale VALUES
(GETDATE()),
(DATEADD(MM, -1, GETDATE())),
(DATEADD(MM, -2, GETDATE())),
(DATEADD(MM, -3, GETDATE())),
(DATEADD(MM, -4, GETDATE())),
(DATEADD(MM, -5, GETDATE()));
